@extends('layouts.public')

@section('title', 'Edit Profil - SIPERMINDA')

@section('content')
    <div class="bg-white border-b shadow-sm"><div class="max-w-3xl mx-auto px-4 py-8 sm:px-6"><p class="text-sm font-semibold uppercase tracking-wider text-primary-600">Akun Pemohon</p><h1 class="mt-1 text-2xl font-bold text-gray-800">Edit Profil</h1><p class="mt-2 text-gray-500">Perbarui informasi Anda. Nomor WhatsApp tetap digunakan sebagai identitas masuk dan tidak dapat diubah di halaman ini.</p></div></div>
    <div class="max-w-3xl mx-auto px-4 py-8 sm:px-6">
        <form method="POST" action="{{ route('pemohon.profil.update') }}" class="rounded-xl border border-gray-200 bg-white p-6 shadow-sm space-y-5" x-data="{ jenisPemohon: '{{ old('jenis_pemohon', $pemohon->jenis_pemohon) }}' }">
            @csrf @method('PUT')
            <div><label class="block text-sm font-medium text-gray-700 mb-1">Nomor WhatsApp</label><input type="text" value="{{ $pemohon->no_hp }}" disabled class="w-full rounded-lg border border-gray-200 bg-gray-100 px-4 py-2.5 text-gray-500"><p class="mt-1 text-xs text-gray-500">Perubahan nomor memerlukan verifikasi OTP ulang dan belum tersedia dari halaman profil.</p></div>
            <div><label for="nama" class="block text-sm font-medium text-gray-700 mb-1">Nama Lengkap</label><input id="nama" name="nama" value="{{ old('nama', $pemohon->nama) }}" required autocomplete="name" class="w-full rounded-lg border border-gray-300 px-4 py-2.5 outline-none focus:border-primary-500 focus:ring-2 focus:ring-primary-500">@error('nama')<p class="mt-1 text-sm text-red-700">{{ $message }}</p>@enderror</div>
            <div><label for="email" class="block text-sm font-medium text-gray-700 mb-1">Email <span class="text-gray-400">(opsional)</span></label><input id="email" type="email" name="email" value="{{ old('email', $pemohon->email) }}" autocomplete="email" class="w-full rounded-lg border border-gray-300 px-4 py-2.5 outline-none focus:border-primary-500 focus:ring-2 focus:ring-primary-500">@error('email')<p class="mt-1 text-sm text-red-700">{{ $message }}</p>@enderror</div>
            <div><label for="jenis_pemohon" class="block text-sm font-medium text-gray-700 mb-1">Kategori Pemohon</label><select id="jenis_pemohon" name="jenis_pemohon" x-model="jenisPemohon" required class="w-full rounded-lg border border-gray-300 px-4 py-2.5 outline-none focus:border-primary-500 focus:ring-2 focus:ring-primary-500"><option value="publik">Publik / Perorangan</option><option value="instansi">Instansi / Organisasi</option></select>@error('jenis_pemohon')<p class="mt-1 text-sm text-red-700">{{ $message }}</p>@enderror</div>
            <div x-show="jenisPemohon === 'instansi'" x-cloak><label for="nama_instansi" class="block text-sm font-medium text-gray-700 mb-1">Asal Instansi/Lembaga</label><input id="nama_instansi" name="nama_instansi" value="{{ old('nama_instansi', $pemohon->nama_instansi) }}" :required="jenisPemohon === 'instansi'" autocomplete="organization" class="w-full rounded-lg border border-gray-300 px-4 py-2.5 outline-none focus:border-primary-500 focus:ring-2 focus:ring-primary-500">@error('nama_instansi')<p class="mt-1 text-sm text-red-700">{{ $message }}</p>@enderror</div>
            <div class="grid gap-5 sm:grid-cols-2"><div><label for="provinsi" class="block text-sm font-medium text-gray-700 mb-1">Provinsi</label><input id="provinsi" name="provinsi" value="{{ old('provinsi', $pemohon->provinsi) }}" required class="w-full rounded-lg border border-gray-300 px-4 py-2.5 outline-none focus:border-primary-500 focus:ring-2 focus:ring-primary-500">@error('provinsi')<p class="mt-1 text-sm text-red-700">{{ $message }}</p>@enderror</div><div><label for="kabupaten_kota" class="block text-sm font-medium text-gray-700 mb-1">Kabupaten/Kota</label><input id="kabupaten_kota" name="kabupaten_kota" value="{{ old('kabupaten_kota', $pemohon->kabupaten_kota) }}" required class="w-full rounded-lg border border-gray-300 px-4 py-2.5 outline-none focus:border-primary-500 focus:ring-2 focus:ring-primary-500">@error('kabupaten_kota')<p class="mt-1 text-sm text-red-700">{{ $message }}</p>@enderror</div></div>
            <div><label for="alamat_lengkap" class="block text-sm font-medium text-gray-700 mb-1">Alamat Lengkap</label><textarea id="alamat_lengkap" name="alamat_lengkap" rows="4" required class="w-full rounded-lg border border-gray-300 px-4 py-2.5 outline-none focus:border-primary-500 focus:ring-2 focus:ring-primary-500">{{ old('alamat_lengkap', $pemohon->alamat_lengkap) }}</textarea>@error('alamat_lengkap')<p class="mt-1 text-sm text-red-700">{{ $message }}</p>@enderror</div>
            <div class="flex flex-col-reverse gap-3 pt-2 sm:flex-row sm:justify-end"><a href="{{ route('pemohon.profil') }}" class="inline-flex justify-center rounded-lg border border-gray-300 px-5 py-3 font-semibold text-gray-700 hover:bg-gray-50">Batal</a><button type="submit" class="inline-flex justify-center rounded-lg bg-primary-600 px-5 py-3 font-semibold text-white hover:bg-primary-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary-500 focus-visible:ring-offset-2">Simpan Perubahan</button></div>
        </form>
    </div>
@endsection
